### ISSUE TITLE
CodeCommit repository is no longer available for new AWS ORG customers

### ISSUE THREAD

**Issue by tbottine** [aws-samples/iam-identity-center-team#285]
**Describe the bug**
When running the ./deploy.sh command, i have this error : 
An error occurred (OperationNotAllowedException) when calling the CreateRepository operation: CreateRepository request is not allowed because there is no existing repository in this AWS account or AWS Organization

**To Reproduce**
1. Go to folder : iam-identity-center-team/deployment
2. Execute script : ./deploy.sh
3. See error

**Expected behavior**
Successful creation of the codecommit repository

**Additional context**
source: https://repost.aws/questions/QUshILm0xbTjWJZSD8afYVgA/codecommit-cannot-create-a-repository

Beginning on 06 June 2024, AWS CodeCommit ceased onboarding new customers. Going forward, only customers who have an existing repository in AWS CodeCommit will be able to create additional repositories.

This change should not impact your current workloads utilizing AWS CodeCommit. If you this is impacting your current workloads, please let us know. If you would like to use AWS CodeCommit in a new AWS account that is part of your AWS Organization, please let us know so that we can evaluate the request for allowlisting the new account. If you would like to use an alternative to AWS CodeCommit given this news, we recommend using Amazon CodeCatalyst, GitLab, GitHub, or another third party source provider of your choice. We have written a blog which describes how to migrate your repository to one of these other solutions.

AWS continues to invest in security, availability, and performance improvements for AWS CodeCommit. You can rely on AWS Support to continue assisting you with any questions you may have about AWS CodeCommit. However, we do not plan to introduce new features to AWS CodeCommit, except for security and availability updates.

If you wish to proceed with an allowlist request, please provide justification via a support case to use the service, and confirm that your organization has been a CodeCommit customer prior to July 25th, 2024.

**Comment by tawoyinfa** [comment]
Thanks @tbottine  for raising this.

**Comment by reidca** [comment]
duplicate of #293

**Comment by danilouchoa** [comment]
I've just connect my gitlab to amplify adn edited the script to ignore aws codecommit commands.

Let me show my amplify.yaml

```yaml
version: 1
backend:
  phases:
    build:
      commands:
        - sudo yum install python3-pip.noarch -y
        - pip3 install pipenv 
        - python3 -m venv app
        - curl -sL https://rpm.nodesource.com/setup_18.x | bash -
        - sudo yum install -y nodejs
        - export PATH="/bin/python3.9:$PATH"
        - virtualenv app
        - npm i graphql-ttl-transformer amplify-prompts@^2.0.1 --prefix /root/.amplify/lib
        - amplifyPush --simple --allow-destructive-graphql-schema-update
frontend:
  phases:
    preBuild:
      commands:
        - npm init -y
        - npm install
        - npm install react-scripts --save && npm ls react-scripts
        - npm ci
    build:
      commands:
        - npm run build
  artifacts:
    baseDirectory: build
    files:
      - '**/*'
  cache:
    paths:
      - node_modules/**/*
```

Now i've the application deployed but i'm not able to login due 

> An error was encountered with the requested page.

![image](https://github.com/user-attachments/assets/ece779c4-0d39-4edd-b554-d8d9c635b1ac)
