### ISSUE TITLE
Incompatibility with New AWS CodeCommit Customers

### ISSUE THREAD

**Issue by CloudNinjaDev** [aws-samples/iam-identity-center-team#336]
**Description**
AWS CodeCommit is no longer available to new customers. As a result, users who were not using CodeCommit before this change can no longer deploy the AWS TEAM application.

**Steps to Reproduce**
Attempt to deploy the AWS TEAM application as a new AWS customer.
I'm afraid it's an issue due to the unavailability of AWS CodeCommit.

**Expected Behavior**
The deployment process should provide flexibility to select a source code provider other than CodeCommit. Specifically, the parameters.sh file should include an option to configure the source code provider, rather than being restricted to CodeCommit.

**Screenshots**
<img width="1056" alt="Screenshot 2024-12-12 at 2 30 17 PM" src="https://github.com/user-attachments/assets/f668f491-7bbe-4785-abc4-b563f5081448" />

**Comment by ehastings-lotame** [comment]
Yes - just discovered this hitch when trying to get deployed!

**Comment by shubha-shyam** [comment]
did any of you successfully deploy the application? i am actually stuck at the same build error because of codecommit.

**Comment by ehastings-lotame** [comment]
Yes - I got it working by making a clone in our own GitLab repo, and configuring a token in Secrets Manager to access it instead.

**Comment by shubha-shyam** [comment]
I tried the same, but it doesn't work for me, I added the projected to my repo and modified the template.yaml with the below entry and referenced the URL.
Is there anything else I need to modify?
  GithubURL:
    Type: String
    Default:

**Comment by CloudNinjaDev** [comment]
So, I also commented out the AWS CodeCommit part from the project and used GitHub in the template file. Here is the working reference for it:
deployment/template.yml
```yml
  AmplifyApp:
    Type: "AWS::Amplify::App"
    Properties:
      Name: TEAM-IDC-APP
      AccessToken: <GITHUB_PAT_HERE>
      Repository: !Sub https://github.com/<ORG_NAME>/<REPO-NAME>.git
      Description: Temporary Elevated Access Management Application
```
